language: node_js
sudo: true
node_js:
  - "4.8"
  - "5.12"
  - "6.10"
  - "7.9"
cache:
  directories:
    - node_modules
before_install:
    - npm install
script:
  - npm run test-ci
after_script:
  - npm run coverage
